### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by chyyran** [SnowflakePowered/chd-rs#1]
## Compatibility
- [x] Read V1-5 header
- [x] Read and decompress V1-5 map 
- [x] Read metadata

## Codecs
- [x] Huffman
- [x] Zlib
- [x] LZMA
  - [x]  Need to test to make sure parameters are OK
- [x] CDLZ
  - [x] Need to write ECC generation 
- [x] CDZL
- [x] CDFL
- [x] AVHU (this one is gnarly, the [MAME implementation](https://github.com/mamedev/mame/blob/master/src/lib/util/avhuff.cpp) makes heavy use of pointer arithmetic that we want to avoid.)
## API
- [x] Read from CHD hunks
- [x] hunk caching
- [x] Rust API Cleanup
    - [x] ChdFile::GetHunk(usize) -> ChdHunk
    - [x] impl Read for ChdHunk
    - [x] impl Read for ChdFile 
- [x] libchdr-compatible bindings
  - [ ] [chd_precache_progress](https://github.com/stenzek/duckstation/blob/master/dep/libchdr/src/libchdr_chd.c#L1538) 
      - This can be done by writing to a `Vec<u8>` and putting ChdFile over the resultant `Vec<u8>`. The C-api for this will involve a bit of fuckery but we can keep the Rust API clean.
   - [ ] Verify bindings

**Comment by chyyran** [comment]
https://github.com/rtissera/libchdr/pull/74
Investigate raw LZMA/FLAC codecs

**Comment by chyyran** [comment]
need a better iterator solution, current `owning_iterators` are trivially unsound

**Comment by chyyran** [comment]
closing in favour of #3 for C API blockers

**Comment by chyyran** [comment]
Ideally AVHU could use additional cleanup but it's not _that_ bad. The bad parts are mostly legacy format.
