### ISSUE TITLE
C API todo list

### ISSUE THREAD

**Issue by chyyran** [SnowflakePowered/chd-rs#3]
- [x] [chd_precache_progress](https://github.com/stenzek/duckstation/blob/master/dep/libchdr/src/libchdr_chd.c#L1538) 
- [x] Shims for https://github.com/rtissera/libchdr/pull/78
    - [x] Since we can not guarantee ABI-compatibility for `chd_file*` (since `libc::FILE*` also does not have a stable ABI) the only thing this involves is defining `chd_open_core_file` to be the same as `chd_open_file`
- [ ] Verify correctness of bindings

**Comment by chyyran** [comment]
https://github.com/SnowflakePowered/chd-rs/commit/3f2b3749e3082e52bed612bff4d842af8e369025 takes care of `chd_precache_progress`/`chd_precache`

**Comment by chyyran** [comment]
pushed docs in https://docs.rs/chd-capi/0.1.3/chd_capi/
